image: docker:latest

stages:
    - build
    - tests

variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    DOCKER_RUN_COMMAND: 'docker run -d --name $CI_PROJECT_NAME --restart=always $IMAGE_NAME'
    CONTAINER_NAME: ${CI_PROJECT_NAME}_${SCHEDULE_NAME}

Build Image:
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"

Start Test:
  stage: tests
  tags:
    - autotests
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - |-
      if [ "$(docker ps -a | grep -c ${CONTAINER_NAME})" -gt 0 ]; then
        docker rm ${CONTAINER_NAME}
      else
        echo "No such container with name ${CONTAINER_NAME}. Nothing to do"
      fi
    - docker pull ${IMAGE_NAME}
    - docker run --name ${CONTAINER_NAME} ${IMAGE_NAME} ${CMD_COMMAND}
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"


